### ISSUE TITLE
Regression test failures against v16

### ISSUE THREAD

**Issue by devrimgunduz** [MigOpsRepos/credcheck#17]
Hi,

credcheck 1.2.0 builds successfully against v16, but regression tests are failing. File is attached.

Can you please take a look?
Thanks! Devrim

[regression.diffs.txt](https://github.com/MigOpsRepos/credcheck/files/11666611/regression.diffs.txt)

**Comment by darold** [comment]
Fixed in version 2.0.0. Note that the new feature "Authentication Failure Ban" requires that package krb5-devel is installed.
