### ISSUE TITLE
Stop harassing users and make checks effective

### ISSUE THREAD

**Issue by davidfetter** [MigOpsRepos/credcheck#2]
While it's tempting to create systems that enforce rules that amount to a regular expression, the effect is to harass users into coming up with passwords that are actually easier to crack than they would be otherwise. Here's an example that's by no means the [earliest](https://arstechnica.com/information-technology/2013/06/password-complexity-rules-more-annoying-less-effective-than-length-ones/).

A much better way to harden passwords against attacks is to use things like checks against databases of leaked passwords like [this one](https://haveibeenpwned.com/Passwords).

Would you be interested in patches that implemented more helpful interventions? I'm thinking that there could be an API that would let people set what amounts to a list of checks to be run, making it easier to adjust same.

**Comment by migopsdinesh** [comment]
Totally agree with you on the points, and thank you for sharing the thoughts on this extension.
It is a nice thought to check the user credentials via an API to an external service, and will keep this as a feature request.

As a first step towards this extension, we have provided few general checks for the users and will make try to make it much better in the further versions.

**Comment by migopsdinesh** [comment]
@davidfetter, yes we are interested in the patches, which would be having the API communication for the credential checks.
Just a thought here, as you already know, most of the production databases will not be having access to the internet,
and it would be great if we can do it with in the application subnet for the credentials checks.
