### ISSUE TITLE
Problem setting credcheck.max_auth_failure

### ISSUE THREAD

**Issue by Gabi201265** [MigOpsRepos/credcheck#20]
Hello, 

I have a problem getting the credcheck.max_auth_failure option to work. I have restarted my server with credcheck added in shared_preload_library, and yet the functionality doesn't work.
My parameter is taken into account:
postgres=# show credcheck.max_auth_failure;
 credcheck.max_auth_failure
 3
(1 row)
And yet : 
postgres=# SELECT * FROM pg_banned_role;
ERROR: relation "pg_banned_role" does not exist
LINE 1: SELECT * FROM pg_banned_role;

I thought it might be my version of postgres because of the encryption (formerly 13.7), so I upgraded to 14.8.
However, it doesn't work any better after the upgrade. I have the impression that credcheck--2.0.0.sql is not played during installation.

Do you have any idea what's wrong?

**Comment by Gabi201265** [comment]
OK, like the old version of password historization, isn't it possible to integrate this feature directly by setting it in the configuration file without having to create the extension?

**Comment by darold** [comment]
No this is not possible, this consist in a C function returning a set of and a view for easy use. It needs DDL to be created into a database to be able to use this view and function. This is the same need of extension creation for pg_stat_statement for example.
