### ISSUE TITLE
credcheck could support defining ENCRYPTED passwords

### ISSUE THREAD

**Issue by ragaoua** [MigOpsRepos/credcheck#21]
When defining a password, credcheck outputs an error if the password is already encrypted :

```
postgres=# ALTER ROLE toto PASSWORD 'SCRAM-SHA-256$4096:KjWZ9rS/wPqDYEUWFswp1A==$M1ZMvgRDsWllX+hx9/vxCgXt1OlrlWkqYPfPq7alm1M=:XlaZ6hdhdvLoc3rKhce/bLwYDFsPdlRmHuNRk/b5/Pw=';
**ERROR:  password type is not a plain text**
```

This is addressed in the documentation as a "limitation", but I think it could be useful to provide a configuration parameter that defines whether or not this way of defining a password is allowed, since defining an already-hashed password is an operation that is necessary in multiple usecases (such as migrations).

A parameter like "encrypted_password_allowed = on/off", with the default being "off", would be very useful.

**Comment by darold** [comment]
I agree, it will be fixed asap.

**Comment by darold** [comment]
Commit 5f7c24e adds the credcheck.encrypted_password_allowed custom configuration variable. It is disabled by default.

**Comment by ragaoua** [comment]
Thank you very much for your diligence !
