### ISSUE TITLE
Failed 03_rename in psql 13

### ISSUE THREAD

**Issue by SengLyhour** [MigOpsRepos/credcheck#23]
Hi Team,
As per my understanding when I use command make installcheck for verify and testing contrib credcheck version 2.1.0
result Failed 03_rename.
![image](https://github.com/MigOpsRepos/credcheck/assets/51234067/0c5b3dd9-d597-4181-b7da-5491409d0761)

My PostgreSQL version 13.9.
Please help me to resolve this issue.

**Comment by df7cb** [comment]
Fwiw, the actual problem is in the `regression.diffs` file. See #24 for a fix.
