### ISSUE TITLE
WARN: page misalignment in file ... pg_password_history

### ISSUE THREAD

**Issue by did16** [MigOpsRepos/credcheck#26]
Hi   
Currently, we are getting the following error message in the log file:
" WARN: page misalignment in file /appli/postgres/passprod/12/data/global/pg_password_history: file size 2604 is not divisible by page size 8192". 
Furthermore, the pgbackrest backups are in error :   
"stanza: passprod-12
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12): 0000000100000019000000B1/000000010000001C00000048

        full backup: 20231130-164557F
            timestamp start/stop: 2023-11-30 16:45:57+01 / 2023-11-30 17:31:36+01
            wal start/stop: 0000000100000019000000B1 / 0000000100000019000000C7
            database size: 78.4GB, database backup size: 78.4GB
            repo1: backup set size: 74.2GB, backup size: 74.2GB
            error(s) detected during backup
"
Is it possible to fix this annoying bug by delivering a corrective version?
Thanks in advance.

**Comment by darold** [comment]
Commit 6639497 fixes this issue by forcing the size of the file to be a multiple of BLCKSZ.

Compile the current development code and install it, restart PostgreSQL. Then create a temporary user with password to force the rewrite of the password history file, size should now be a multiple of 8192.
