### ISSUE TITLE
pg_password_history and pgbackrest

### ISSUE THREAD

**Issue by glushakov** [MigOpsRepos/credcheck#32]
Hi. 
When using password reuse policy with pgbackrest, in log files appears:
WARN: invalid page checksum found in file /var/lib/pgsql/16/data/global/pg_password_history at page 0
and in summary info: "error(s) detected during backup" which really confused.
Is there any way to avoid this?
pgbackrest-2.51 , credcheck 2.6

**Comment by darold** [comment]
The only way is to move the password history file elsewhere than in the global sub-directory. Actually I had always though that this was a very bad idea to store this file there, but it appears to me that it should be the best place to write it. No I know I was first right :-D I will move it to PGDATA directly.

**Comment by glushakov** [comment]
Thanks a lot!

**Comment by glushakov** [comment]
Please tell, when we can expect a release with this fix?

**Comment by darold** [comment]
Release [v2.7](https://github.com/MigOpsRepos/credcheck/releases/tag/v2.7) published.
