### ISSUE TITLE
2.7 fails to build against PostgreSQL 17

### ISSUE THREAD

**Issue by devrimgunduz** [MigOpsRepos/credcheck#35]
Hi,

v17 Beta1 is out, and credcheck 2.7 fails to build against it. Can you please take a look? Thanks! Devrim

> + PATH=/usr/pgsql-17/bin:/home/devrim/Downloads/google-cloud-sdk/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/devrim/bin/:/home/devrim/bin/
+ /usr/bin/make -j14
make[1]: Entering directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/main/non-common/credcheck/main/credcheck-2.7'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -Wno-ignored-attributes -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include  -c -o credcheck.o credcheck.c
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -Wno-ignored-attributes -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o credcheck.bc credcheck.c
credcheck.c:2121:2: error: call to undeclared function 'tuplestore_donestoring'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2121 |         tuplestore_donestoring(tupstore);
      |         ^
credcheck.c:2481:2: error: call to undeclared function 'tuplestore_donestoring'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2481 |         tuplestore_donestoring(tupstore);
      |         ^
2 errors generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: credcheck.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
credcheck.c: In function ‘pg_password_history_internal’:
credcheck.c:2121:9: error: implicit declaration of function ‘tuplestore_donestoring’; did you mean ‘tuplestore_rescan’? [-Wimplicit-function-declaration]
 2121 |         tuplestore_donestoring(tupstore);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         tuplestore_rescan
make[1]: *** [<builtin>: credcheck.o] Error 1

**Comment by darold** [comment]
Thanks Devrim, this issue have already been fixed with commit 449e896, I will publish a new version asap.

**Comment by devrimgunduz** [comment]
Thanks! When can we see a new release?

**Comment by devrimgunduz** [comment]
ping.

**Comment by darold** [comment]
Done, sorry for the delay.
