### ISSUE TITLE
Build error against PostgreSQL 14

### ISSUE THREAD

**Issue by devrimgunduz** [MigOpsRepos/credcheck#4]
Hi,

credcheck fails to build against v14. Can you please take a look? logs are below.

Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o credcheck.o credcheck.c
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o credcheck.bc credcheck.c
credcheck.c: In function '_PG_init':
credcheck.c:563:29: warning: assignment to 'ProcessUtility_hook_type' {aka 'void (*)(PlannedStmt *, const char *, _Bool,  ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, struct _DestReceiver *, QueryCompletion *)'} from incompatible pointer type 'void (*)(PlannedStmt *, const char *, ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, DestReceiver *, QueryCompletion *)' {aka 'void (*)(PlannedStmt *, const char *, ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, struct _DestReceiver *, QueryCompletion *)'} [-Wincompatible-pointer-types]
  563 |         ProcessUtility_hook = cc_ProcessUtility;
      |                             ^
credcheck.c: In function 'cc_ProcessUtility':
credcheck.c:52:62: error: incompatible type for argument 4 of 'prev_ProcessUtility'
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                              ^~~~~~
      |                                                              |
      |                                                              ParamListInfo {aka struct ParamListInfoData *}
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:52:62: note: expected 'ProcessUtilityContext' but argument is of type 'ParamListInfo' {aka 'struct ParamListInfoData *'}
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                              ^~~~~~
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:52:70: warning: passing argument 5 of 'prev_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                      ^~~~~~~~
      |                                                                      |
      |                                                                      QueryEnvironment *
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:52:70: note: expected 'ParamListInfo' {aka 'struct ParamListInfoData *'} but argument is of type 'QueryEnvironment *'
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                      ^~~~~~~~
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:52:80: warning: passing argument 6 of 'prev_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                                ^~~~
      |                                                                                |
      |                                                                                DestReceiver * {aka struct _DestReceiver *}
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:52:80: note: expected 'QueryEnvironment *' but argument is of type 'DestReceiver *' {aka 'struct _DestReceiver *'}
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                                ^~~~
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:52:86: warning: passing argument 7 of 'prev_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                                      ^~
      |                                                                                      |
      |                                                                                      QueryCompletion *
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:52:86: note: expected 'DestReceiver *' {aka 'struct _DestReceiver *'} but argument is of type 'QueryCompletion *'
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                                      ^~
credcheck.c:642:37: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
credcheck.c:642:17: error: too few arguments to function 'prev_ProcessUtility'
  642 |                 prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                 ^~~~~~~~~~~~~~~~~~~
credcheck.c:52:62: error: incompatible type for argument 4 of 'standard_ProcessUtility'
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                              ^~~~~~
      |                                                              |
      |                                                              ParamListInfo {aka struct ParamListInfoData *}
credcheck.c:644:41: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  644 |                 standard_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from credcheck.c:29:
/usr/pgsql-14/include/server/tcop/utility.h:87:95: note: expected 'ProcessUtilityContext' but argument is of type 'ParamListInfo' {aka 'struct ParamListInfoData *'}
   87 |                                                                         ProcessUtilityContext context, ParamListInfo params,
      |                                                                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
credcheck.c:52:70: warning: passing argument 5 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                      ^~~~~~~~
      |                                                                      |
      |                                                                      QueryEnvironment *
credcheck.c:644:41: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  644 |                 standard_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from credcheck.c:29:
/usr/pgsql-14/include/server/tcop/utility.h:87:118: note: expected 'ParamListInfo' {aka 'struct ParamListInfoData *'} but argument is of type 'QueryEnvironment *'
   87 |                                                                         ProcessUtilityContext context, ParamListInfo params,
      |                                                                                                        ~~~~~~~~~~~~~~^~~~~~
credcheck.c:52:80: warning: passing argument 6 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                                ^~~~
      |                                                                                |
      |                                                                                DestReceiver * {aka struct _DestReceiver *}
credcheck.c:644:41: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  644 |                 standard_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from credcheck.c:29:
/usr/pgsql-14/include/server/tcop/utility.h:88:91: note: expected 'QueryEnvironment *' but argument is of type 'DestReceiver *' {aka 'struct _DestReceiver *'}
   88 |                                                                         QueryEnvironment *queryEnv,
      |                                                                         ~~~~~~~~~~~~~~~~~~^~~~~~~~
credcheck.c:52:86: warning: passing argument 7 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   52 | #define PEL_PROCESSUTILITY_ARGS pstmt, queryString, context, params, queryEnv, dest, qc
      |                                                                                      ^~
      |                                                                                      |
      |                                                                                      QueryCompletion *
credcheck.c:644:41: note: in expansion of macro 'PEL_PROCESSUTILITY_ARGS'
  644 |                 standard_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from credcheck.c:29:
/usr/pgsql-14/include/server/tcop/utility.h:89:87: note: expected 'DestReceiver *' {aka 'struct _DestReceiver *'} but argument is of type 'QueryCompletion *'
   89 |                                                                         DestReceiver *dest, QueryCompletion *qc);
      |                                                                         ~~~~~~~~~~~~~~^~~~
credcheck.c:644:17: error: too few arguments to function 'standard_ProcessUtility'
  644 |                 standard_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
In file included from credcheck.c:29:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: declared here
   85 | extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: credcheck.o] Error 1
make[1]: *** Waiting for unfinished jobs....
credcheck.c:563:22: warning: incompatible function pointer types assigning to 'ProcessUtility_hook_type' (aka 'void (*)(struct PlannedStmt *, const char *, bool, ProcessUtilityContext, struct ParamListInfoData *, struct QueryEnvironment *, struct _DestReceiver *, struct QueryCompletion *)') from 'void (PlannedStmt *, const char *, ProcessUtilityContext, ParamListInfo, QueryEnvironment *, DestReceiver *, QueryCompletion *)' (aka 'void (struct PlannedStmt *, const char *, ProcessUtilityContext, struct ParamListInfoData *, struct QueryEnvironment *, struct _DestReceiver *, struct QueryCompletion *)') [-Wincompatible-function-pointer-types]
        ProcessUtility_hook = cc_ProcessUtility;
                            ^ ~~~~~~~~~~~~~~~~~
credcheck.c:642:46: error: too few arguments to function call, expected 8, have 7
                prev_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
                ~~~~~~~~~~~~~~~~~~~                        ^
credcheck.c:644:50: error: too few arguments to function call, expected 8, have 7
                standard_ProcessUtility(PEL_PROCESSUTILITY_ARGS);
                ~~~~~~~~~~~~~~~~~~~~~~~                        ^
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: 'standard_ProcessUtility' declared here
extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
            ^
1 warning and 2 errors generated.
make[1]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/Makefile.global:1070: credcheck.bc] Error 1

**Comment by darold** [comment]
Hi Devrim,

Thanks for the report, I have fixed the issue and also the extension upgrade scripts that was missing. A new release 0.2.0 have been published. Let us know if there is any remaining issues.

Cheers,

**Comment by devrimgunduz** [comment]
@darold thanks a lot! 0.2.0 builds fine.

Cheers, Devrim
