### ISSUE TITLE
Support for encrypted passwords

### ISSUE THREAD

**Issue by umairshahid** [MigOpsRepos/credcheck#6]
This comes in from an interview with a customer, they need support for encrypted passwords as part of regulatory compliance.

**Comment by darold** [comment]
It is not possible to know the plain text value of an encrypted password passed to a CREATE or ALTER ROLE statement. The credential strength must be checked by the utility used to generate the encrypted password.

**Comment by jobinau** [comment]
@umairshahid , Technically it is impossible for the server to know the password strength if it is encrypted on the client-side.
Sad, but it defeats some of the good practices and feature provided in `psql`
```
postgres=# \password abc  
Enter new password:  
Enter it again:   
ERROR:  password type is not a plain text  
```
